name: clang

on:
  push:
    branches:
    - main
    - feature/*
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    
    strategy:
      fail-fast: false
      matrix:
        clang: [15, 16, 18]
        build_type: [Debug, Release]
        std: [20, 23]

    env:
      CC: clang-${{matrix.clang}}
      CXX: clang++-${{matrix.clang}}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_CXX_STANDARD=${{matrix.std}} \
          -DCMAKE_C_COMPILER=${{env.CC}} \
          -DCMAKE_CXX_COMPILER=${{env.CXX}} \
          -DCLANG_LIBCXX=ON

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      run: ctest -j 2 --output-on-failure
