name: disable-always-inline

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  gcc15:
    runs-on: ubuntu-26.04

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        std: [23]

    env:
      CC: gcc-15
      CXX: g++-15

    steps:
    - uses: actions/checkout@v6

    - name: Configure CMake
      run: |
        cmake -S "$GITHUB_WORKSPACE" -B "$GITHUB_WORKSPACE/build" \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_CXX_STANDARD=${{matrix.std}} \
          -Dglaze_DISABLE_ALWAYS_INLINE=ON \
          -Dglaze_BUILD_PERFORMANCE_TESTS=OFF \
          -Dglaze_BUILD_NETWORKING_TESTS=OFF

    - name: Build
      run: cmake --build "$GITHUB_WORKSPACE/build" -j $(nproc)

    - name: Test
      run: ctest --output-on-failure --test-dir "$GITHUB_WORKSPACE/build"

  clang22:
    runs-on: ubuntu-26.04

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        std: [23]

    env:
      CC: clang-22
      CXX: clang++-22
      LLVM_VERSION: 22

    steps:
    - uses: actions/checkout@v6

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_CXX_STANDARD=${{matrix.std}} \
          -DCMAKE_C_COMPILER=${{env.CC}} \
          -DCMAKE_CXX_COMPILER=${{env.CXX}} \
          -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
          -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -lc++abi" \
          -Dglaze_DISABLE_ALWAYS_INLINE=ON \
          -Dglaze_BUILD_PERFORMANCE_TESTS=OFF \
          -Dglaze_BUILD_NETWORKING_TESTS=OFF

    - name: Build
      run: cmake --build build -j $(nproc)

    - name: Test
      working-directory: build
      run: ctest -j $(nproc) --output-on-failure
