name: gcc-linux-latest

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]
        std: [23]

    env:
      CC: gcc
      CXX: g++

    steps:
    - uses: actions/checkout@v4

    - name: Add Ubuntu Toolchain Test PPA and Install GCC 15
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y gcc-15 g++-15

    - name: Set GCC 15 as Default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 100 \
                                 --slave /usr/bin/g++ g++ /usr/bin/g++-15
        sudo update-alternatives --set gcc /usr/bin/gcc-15
        gcc --version
        g++ --version

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_CXX_STANDARD=${{matrix.std}} \
          -DCMAKE_C_COMPILER=${{env.CC}} \
          -DCMAKE_CXX_COMPILER=${{env.CXX}}

    - name: Build
      run: cmake --build build -j $(nproc)

    - name: Test
      working-directory: build
      run: ctest -j $(nproc) --output-on-failure
