name: gcc-linux-latest
# This workflow sets up and tests with the latest GCC (15)

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]
        std: [23]

    env:
      CC: gcc
      CXX: g++

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libgmp-dev libmpfr-dev libmpc-dev flex bison wget

    - name: Download and extract GCC 15.1
      run: |
        wget https://ftp.gnu.org/gnu/gcc/gcc-15.1.0/gcc-15.1.0.tar.gz
        tar -xzf gcc-15.1.0.tar.gz
        mkdir gcc-15.1.0/build
        cd gcc-15.1.0/build
        ../configure --prefix=/opt/gcc-15.1 --enable-languages=c,c++ --disable-multilib
        make -j$(nproc)
        sudo make install

    - name: Set GCC 15 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /opt/gcc-15.1/bin/gcc 100
        sudo update-alternatives --install /usr/bin/g++ g++ /opt/gcc-15.1/bin/g++ 100
        gcc --version
        g++ --version

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_CXX_STANDARD=${{matrix.std}} \
          -DCMAKE_C_COMPILER=${{env.CC}} \
          -DCMAKE_CXX_COMPILER=${{env.CXX}}

    - name: Build
      run: cmake --build build -j $(nproc)

    - name: Test
      working-directory: build
      run: ctest -j $(nproc) --output-on-failure
