name: gcc

on:
  push:
    branches:
    - main
    - feature/*
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    
    strategy:
      fail-fast: false
      matrix:
        gcc: [12, 13, 14]
        build_type: [Debug, Release]
        std: [20, 23]

    env:
      CC: gcc-${{matrix.gcc}} -m32
      CXX: g++-${{matrix.gcc}} -m32

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install g++-multilib

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{matrix.std}} -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      run: ctest -j 2 --output-on-failure
