name: gcc12

on:
  push:
    branches:
    - main
    - feature/*
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
    - '**.md'
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      CC: gcc-12
      CXX: g++-12
    
    strategy:
      fail-fast: false
      matrix:
        std: [20, 23]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{matrix.std}}

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      run: ctest -j 2 --output-on-failure
