name: msvc

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025-vs2026
    timeout-minutes: 60

    strategy:
      matrix:
        cpp_version: [23]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v6

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{matrix.cpp_version}}

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}} --parallel

    - name: Test
      working-directory: build
      run: ctest --output-on-failure --build-config ${{matrix.build_type}} --timeout 300
