name: quickfuzz

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        clang: [19]
        build_type: [Debug]
        std: [23]

    env:
      CC: clang-${{matrix.clang}}
      CXX: clang++-${{matrix.clang}}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-19

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_CXX_STANDARD=${{matrix.std}} \
          -DCMAKE_C_COMPILER=${{env.CC}} \
          -DCMAKE_CXX_COMPILER=${{env.CXX}} \
          -DBUILD_TESTING=Off

    - name: Build
      run: cmake --build build -j $(nproc)

    - name: Test
      working-directory: build
      run: |        
        set -e
        mkdir -p corpus

        echo number of cpus: $(nproc)
        echo amount of ram:
        free -h

        ../fuzzing/quickfuzz/run_all.sh

        echo all is OK!

    - uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: fuzzing-artifacts
        path: build/artifacts/

